# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-10 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20191109_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
    ]
